apiVersion: v1
kind: ConfigMap
metadata:
    name: ixiatg-release-config
    namespace: ixiatg-op-system
data:
    versions: |
        {
          "release": "0.0.1-2765-local",
          "images": [
                {
                    "name": "controller",
                    "path": "us-central1-docker.pkg.dev/kt-nts-athena-dev/keysight/ixia-c-controller",
                    "tag": "0.0.1-2765"
                },
                {
                    "name": "gnmi-server",
                    "path": "us-central1-docker.pkg.dev/kt-nts-athena-dev/keysight/ixia-c-gnmi-server",
                    "tag": "1.7.13"
                },
                {
                    "name": "grpc-server",
                    "path": "us-central1-docker.pkg.dev/kt-nts-athena-dev/keysight/ixia-c-grpc-server",
                    "tag": "0.7.8"
                },
                {
                    "name": "traffic-engine",
                    "path": "us-central1-docker.pkg.dev/kt-nts-athena-dev/keysight/ixia-c-traffic-engine",
                    "tag": "1.0.0.277"
                },
                {
                    "name": "protocol-engine",
                    "path": "us-central1-docker.pkg.dev/kt-nts-athena-dev/keysight/ixia-c-protocol-engine",
                    "tag": "1.00.0.154"
                }
            ]
        }
