apiVersion: v1
kind: ConfigMap
metadata:
    name: ixiatg-release-config
    namespace: ixiatg-op-system
data:
    versions: |
        {
          "release": "0.0.1-2770-local",
          "images": [
                {
                    "name": "controller",
                    "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-controller",
                    "tag": "0.0.1-2770"
                },
                {
                    "name": "gnmi-server",
                    "path": "ixiacom/ixia-c-gnmi-server",
                    "tag": "1.7.13"
                },
                {
                    "name": "grpc-server",
                    "path": "ixiacom/ixia-c-grpc-server",
                    "tag": "0.7.8"
                },
                {
                    "name": "traffic-engine",
                    "path": "ixiacom/ixia-c-traffic-engine",
                    "tag": "1.0.0.275"
                },
                {
                    "name": "protocol-engine",
                    "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine",
                    "tag": "1.00.0.154"
                }
            ]
        }
