apiVersion: v1
kind: ConfigMap
metadata:
    name: ixiatg-release-config
    namespace: ixiatg-op-system
data:
    versions: |
        {
          "release": "0.0.1-2677-local",
          "images": [
                {
                    "name": "ghcr.io/open-traffic-generator/controller",
                    "path": "ixia-c-controller",
                    "tag": "0.0.1-2677"
                },
                {
                    "name": "gnmi-server",
                    "path": "ixiacom/ixia-c-gnmi-server",
                    "tag": "0.7.5"
                },
                {
                    "name": "grpc-server",
                    "path": "ixiacom/ixia-c-grpc-server",
                    "tag": "0.7.7"
                },
                {
                    "name": "traffic-engine",
                    "path": "ixiacom/ixia-c-traffic-engine",
                    "tag": "1.4.1.23"
                },
                {
                    "name": "ghcr.io/open-traffic-generator/protocol-engine",
                    "path": "ixia-c-protocol-engine",
                    "tag": "1.00.0.145"
                }
            ]
        }
