apiVersion: v1
kind: ConfigMap
metadata:
  name: ixiatg-release-config
  namespace: ixiatg-op-system
data:
  versions: |
    {
      "release": "0.0.1-2543-local",
      "images": [
            {
                "name": "controller",
                "path": "ghcr.io/open-traffic-generator/ixia-c-controller",
                "tag": "0.0.1-2543"
            },
            {
                "name": "gnmi-server",
                "path": "ixiacom/ixia-c-gnmi-server",
                "tag": "0.7.2"
            },
            {
                "name": "grpc-server",
                "path": "ixiacom/ixia-c-grpc-server",
                "tag": "0.7.2"
            },
            {
                "name": "traffic-engine",
                "path": "ixiacom/ixia-c-traffic-engine",
                "tag": "1.4.1.2"
            },
            {
                "name": "protocol-engine",
                "path": "ghcr.io/open-traffic-generator/ixia-c-protocol-engine",
                "tag": "1.00.0.127"
            }
        ]
    }
